name: Build and Publish Artifact

on:
  workflow_dispatch:
      

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17' # Adjust this to your Java version
          distribution: 'adopt' # Specify the desired Linux distribution

      - name: Build
        run: |
          ./gradlew clean build
